export default [
  {
    id: 1,
    link: "https://www.udemy.com/course/pythonforbeginners/",
    title: "Learn Python: The Complete Python Programming Course",
    description:
      "Learn A-Z everything about Python, from the basics, to advanced topics like Python GUI, Python Data Analysis, and more!",
    author: "Avinash Jain,The Codex",
    image: "https://img-c.udemycdn.com/course/240x135/394676_ce3d_5.jpg",
    price: "679.99",
    rating: 4.4,
    people: "2,948",
    category: "python",
    bestseller: false,
    learnings: [
      "Create their own Python Programs",
      "Become an experienced Python Programmer",
      "Parse the Web and Create their own Games",
    ],
    requirements: [
      "Macintosh (OSX)/ Windows(Vista and higher) Machine",
      "Internet Connection",
    ],
    content: [
      [["Up and Running With Python"], ["Installing Python", "Hello World"]],
      [
        ["The Basics (Data Types)"],
        [
          "Variables",
          "Multiple Assignment",
          "Data Types and Ints",
          "Strings",
          "Placeholders",
          "Lists/Arrays",
          "List Functions",
          "Dictionaries",
          "Dictionary Functions",
          "Tuples",
          "Exercise Files",
        ],
      ],
      [
        ["Conditions and Loops"],
        [
          "If-Else Statements",
          "Relational Operators",
          "Nested If/Else",
          "Elif Statements",
          "Logical Operators",
          "For Loops",
          "While Loops",
          "Nested For Loops",
          "Pass, Break and Continue",
          "Try and Except",
          "Commenting",
          "Quick Tips",
          "Exercise Files",
        ],
      ],
      [
        ["Functions!"],
        [
          "Creating our own Functions",
          "Global and Local Vars",
          "Abs and Bool",
          "Help and Dir",
          "Eval and Exec",
          "Str, Int, Float",
          "Recap and Sum",
        ],
      ],
      [
        ["Classes! (Object Orientated Programming)"],
        [
          "Basics of Classes",
          "Functions in Classes",
          "Class Attributes",
          "Inheritance",
          "Overriding Methods",
        ],
      ],
      [
        ["File Input/Output"],
        [
          "Creating a File",
          "Creating a File (Windows)",
          "Reading a File",
          "Writing to a File",
          "Appending to Files",
          "Copying Files",
        ],
      ],
      [
        ["Using Python Modules"],
        [
          "Random Module - Randint",
          "Guessing Game",
          "Guessing Game Challenge",
          "Random Module - Shuffle and Choice",
          "Sys Module",
          "Time Module",
          "Turtle Module",
          "For Loops in Turtle",
          "Up and Down Functions",
          "Coloring in Turtle",
          "Functions in Turtle",
          "Exercise Files",
        ],
      ],
      [
        ["Crawling The Web"],
        [
          "Re Module",
          "Crawling The Web (Stocks)",
          "Stock Quotes (.py)",
          "Crawling The Web (Weather)",
          "Weather (.py)",
          "Crawling The Web (Definition)",
          "Definition (.py)",
        ],
      ],
      [
        ["Beautiful Soup HTML Parsing"],
        [
          "Intro to Beautiful Soup",
          "Installing the Beautiful Soup Module",
          "Prettify with Soup",
          "Drilling Down",
          "Functions in Soup",
          ".String and .Parent",
          "Searching in Soup",
          "Weather Parsing",
          "Antonym Parsing",
        ],
      ],
      [
        ["MatPlotLib - Charts, Plots and 3D Figures!"],
        [
          "Intro to MatPlotLib",
          "First Graph!",
          "Understanding the MatPlotLib Interface",
          "Graph Labels",
          "Creating a Graph from a File",
          "Understanding SubPlots and Figures",
          "Coloring of Graph",
          "Multiple Plots in a Graph",
          "Multiple Graphs in a Figure",
          "What about 3 graphs?",
          "Bar Graphs Intro",
          "Modifying our Bar Graph",
          "Pie Chart Intro",
          "Modifying our Pie Chart",
          "Adding a Legend",
          "3D Graphics Intro",
          "3D Scatter Plots",
          "Multiple 3D Scatter Plots",
          "3D Bar Graphs",
          "3D Wireframes",
        ],
      ],
      [
        ["Data Analysis with Pandas!"],
        [
          "Intro to Pandas",
          "Series Data Structure",
          "Series Continuation",
          "Data Frames Intro",
          "Creating a CSV",
          "Reading a CSV",
          "Writing to a CSV",
          "Getting our Data",
          "Slicing Data Frames",
          "Data Manipulation",
          "Indexing and More",
          "Merging Data Frames",
          "GroupBy Function",
          "MovieLens Data",
          "Heavy Data Analysis",
          "MatPlotLib with Pandas",
          "Let's Finish This",
        ],
      ],
      [
        ["Python GUI with Tkinter"],
        [
          "Tkinter Introduction",
          "Labels",
          "Buttons",
          "Layouts",
          "Fill",
          "Grid Layout",
          "Entries",
          "Check Buttons",
          "GUI Login",
          "Actions on Button Click",
          "Binding Functions",
          "More Binding!",
          "Getting Entry Data",
          "Message Box",
          "Drop Down Menus",
          "Calculator Part 1",
          "Calculator Part 2",
          "Calculator Part 3",
          "Calculator Part 4",
          "Canvas Intro",
          "Canvas Objects",
          "Canvas Fill",
          "Random Rectangle Generator",
          "Text and Arcs",
          "Animations",
        ],
      ],
      [
        ["Our First Game (Bounce!)"],
        [
          "Creating our Ball",
          "Adding the Game Interface",
          "Adding the Paddle",
          "Final Touches",
          "Recap",
          "Bounce! (.py) (v1/v2/v3)",
        ],
      ],
      [
        ["Our Second Game (Pong!)"],
        [
          "Creating our Ball",
          "Adding Paddle1",
          "Adding Paddle2",
          "Final Touches",
          "Pong! (.py)",
        ],
      ],
      [["What's Next?"], ["Up and Beyond!"]],
    ],
  },
  {
    id: 2,
    link: "https://www.udemy.com/course/learning-python-for-data-analysis-and-visualization/",
    title: "Learning Python for Data Analysis and Visualization",
    description:
      "Learn python and how to use it to analyze,visualize and present data. Includes tons of sample code and hours of video!",
    author: "Jose Portilla",
    image: "https://img-c.udemycdn.com/course/240x135/396876_cc92_7.jpg",
    price: "1,599.99",
    rating: 4.4,
    people: "1,019",
    category: "python",
    bestseller: true,
    learnings: [
      "Have an intermediate skill level of Python programming.",
      "Use the Jupyter Notebook Environment.",
      "Use the numpy library to create and manipulate arrays.",
      "Use the pandas module with Python to create and structure data.",
      "Learn how to work with various data formats within python, including: JSON,HTML, and MS Excel Worksheets.",
      "Create data visualizations using matplotlib and the seaborn modules with python.",
      "Have a portfolio of various data analysis projects.",
    ],
    content: [
      [
        ["Programming fundamentals"],
        [
          "Introduction",
          "What is programming?",
          "What is source code?",
          "Compile VS Interpreted Languages",
          "Strings and numbers",
          "Variables",
          "Lists, Arrays or Collections",
          "Conditional Code - If statements",
          "Loops",
          "Functions",
        ],
      ],
      [
        ["Getting Started with Python"],
        [
          "intro to getting started",
          "What is Python?",
          "Installing Python",
          "Running Python IDLE and online",
          "Installing IDE",
        ],
      ],
      [
        ["Python Basics"],
        [
          "Intro to python basics",
          "Exercise files",
          "Strings  &amp; print function",
          "Numbers / Math",
          "Variables",
          "Lists",
          "Tuples",
          "Dictionaries",
        ],
      ],
      [
        ["Conditional structures"],
        [
          "intro to conditional code",
          "If Statements",
          "While Loop",
          "For loop",
          "Break and Continue",
        ],
      ],
      [
        ["Functions"],
        [
          "intro to functions",
          "Custom Functions &amp; arguments",
          "Functions with arguments",
          "Function variable scopes",
          "Function return",
          "Functions with flexible arguments",
          "Unpacking",
          "Modules",
          "Built in functions",
        ],
      ],
      [
        ["Working with files"],
        [
          "Intro to working files",
          "Opening / Creating files / Writing files",
          "File reading",
          "Renaming files",
          "Deleting files",
        ],
      ],
    ],
  },
  {
    id: 3,
    link: "https://www.udemy.com/course/python-for-beginners-learn-programming-from-scratch/",
    title: "Python for Beginners - Learn Programming from scratch",
    description:
      "Learn python and how to use it to analyze,visualize and present data. Includes tons of sample code and hours of video!",
    author: "Edwin Diaz, Coding Facutly Solutions",
    image: "https://img-c.udemycdn.com/course/240x135/405878_e5a0_3.jpg",
    price: "679.99",
    rating: 4.4,
    people: "1,781",
    category: "python",
    bestseller: false,
    learnings: [
      "To learn the python language",
      "To learn the CORE skills to understand any programming language",
    ],
    content: [
      [
        ["Programming fundamentals"],
        [
          "Introduction",
          "What is programming?",
          "What is source code?",
          "Compile VS Interpreted Languages",
          "Strings and numbers",
          "Variables",
          "Lists, Arrays or Collections",
          "Conditional Code - If statements",
          "Loops",
          "Functions",
        ],
      ],
      [
        ["Getting Started with Python"],
        [
          "intro to getting started",
          "What is Python?",
          "Installing Python",
          "Running Python IDLE and online",
          "Installing IDE",
        ],
      ],
      [
        ["Python Basics"],
        [
          "Intro to python basics",
          "Exercise files",
          "Strings  &amp; print function",
          "Numbers / Math",
          "Variables",
          "Lists",
          "Tuples",
          "Dictionaries",
        ],
      ],
      [
        ["Conditional structures"],
        [
          "intro to conditional code",
          "If Statements",
          "While Loop",
          "For loop",
          "Break and Continue",
        ],
      ],
      [
        ["Functions"],
        [
          "intro to functions",
          "Custom Functions &amp; arguments",
          "Functions with arguments",
          "Function variable scopes",
          "Function return",
          "Functions with flexible arguments",
          "Unpacking",
          "Modules",
          "Built in functions",
        ],
      ],
      [
        ["Working with files"],
        [
          "Intro to working files",
          "Opening / Creating files / Writing files",
          "File reading",
          "Renaming files",
          "Deleting files",
        ],
      ],
    ],
    instructor: 1,
  },
  {
    id: 13,
    link: "https://www.udemy.com/course/complete-python-bootcamp/",
    title: "Introduction to Web Development",
    author: "Mark Lassoff",
    image: "https://img-b.udemycdn.com/course/240x135/99986_6cb4_10.jpg",
    price: "229.99",
    rating: 4.3,
    people: "1,734",
    category: "web development",
    bestseller: true,
    content: [
      [
        ["Tools and HTML"],
        [
          "Introduction",
          "Development Tools",
          "Getting Started with HTML",
          "Images on web pages",
          "Section 1 Lab Exercise",
        ],
      ],
      [
        ["CSS"],
        [
          "Introducing CSS",
          "Using Color",
          "Box Model",
          "Section 2 Lab Exercise",
        ],
      ],
      [
        ["Javascript"],
        [
          "Inserting Javascript",
          "Writing Javascript",
          "Making a Form",
          "Where to Go From Here?",
          "Section 3 Lab Exercise",
        ],
      ],
      [["Bonus Lecture"], ["Bonus Lecture"]],
    ],
  },
  {
    id: 15,
    link: "https://www.udemy.com/course/complete-python-bootcamp/",
    title: "Microsoft Excel 2013 Course Beginners/ Intermediate Training",
    author: "Infinite Skills",
    image: "https://img-b.udemycdn.com/course/240x135/31535_e351_7.jpg",
    price: "519.99",
    rating: 4.6,
    people: "1,153",
    category: "excel",
    bestseller: false,
  },
  {
    id: 16,
    link: "https://www.udemy.com/course/complete-python-bootcamp/",
    title: "Microsoft Excel 2013 Advanced. Online Excel Training Course",
    author: "Infinite Skills",
    image: "https://img-b.udemycdn.com/course/240x135/39292_b3f3_9.jpg",
    price: "519.99",
    rating: 4.5,
    people: "3,534",
    category: "excel",
    bestseller: false,
  },
  {
    id: 17,
    link: "",
    title: "Microsoft Excel - From Beginner to Expert in 6 Hours",
    author: "Todd McLeod",
    image: "https://img-b.udemycdn.com/course/240x135/49250_a658_8.jpg",
    price: "269.99",
    rating: 4.6,
    people: "24,534",
    category: "excel",
    bestseller: true,
  },
  {
    id: 18,
    link: "https://www.udemy.com/course/automate/",
    title: "The Complete JavaScript Course 2022: From Zero to Expert!",
    author: "Jonas Schmedtmann",
    image: "https://img-b.udemycdn.com/course/240x135/851712_fc61_6.jpg",
    price: "1699.99",
    rating: 4.8,
    people: "97,703",
    category: "java script",
    bestseller: true,
  },
  {
    id: 19,
    link: "https://www.udemy.com/course/complete-python-bootcamp/",
    title: "1 Hour JavaScript",
    author: "John Bura",
    image: "https://img-b.udemycdn.com/course/240x135/63612_8797_4.jpg",
    price: "299.99",
    rating: 4.4,
    people: "1,893",
    category: "java script",
    bestseller: false,
  },
  {
    id: 20,
    link: "https://www.udemy.com/course/complete-python-bootcamp/",
    title: "Javascript for Beginners",
    author: "Tech learning Network",
    image: "https://img-b.udemycdn.com/course/240x135/8324_fa84_13.jpg",
    price: "179.99",
    rating: 4.5,
    people: "734",
    category: "java script",
    bestseller: false,
  },
  {
    id: 21,
    link: "https://www.udemy.com/course/complete-python-bootcamp/",
    title: "JavaScript from Beginner to Expert",
    author: "Arkadiusz Włodarczyk",
    image: "https://img-b.udemycdn.com/course/240x135/426196_3cb8_4.jpg",
    price: "829.99",
    rating: 4.5,
    people: "1,153",
    category: "java script",
    bestseller: false,
  },
  {
    id: 22,
    link: "https://www.udemy.com/course/complete-python-bootcamp/",
    title: "ES6 Javascript: The Complete Developer's Guide",
    author: "Stephan Grider",
    image: "https://img-b.udemycdn.com/course/240x135/861624_864d_2.jpg",
    price: "619.99",
    rating: 4.7,
    people: "12,089",
    category: "java script",
    bestseller: true,
  },
  {
    id: 23,
    link: "",
    title: "Learning Data Structures in JavaScript from Scratch",
    author: "Eric Traub",
    image: "https://img-b.udemycdn.com/course/240x135/973918_93b1_2.jpg",
    price: "1,199.99",
    rating: 4.8,
    people: "2,071",
    category: "java script",
    bestseller: false,
  },
  {
    id: 24,
    link: "",
    title: "Data Science and Machine Learning Bootcamp with R",
    author: "Jose Portilla",
    image: "https://img-b.udemycdn.com/course/240x135/821726_8071.jpg",
    price: "1,599.99",
    rating: 4.8,
    people: "15,071",
    category: "data science",
    bestseller: false,
  },
  {
    id: 25,
    link: "",
    title: "AWS Certified Security Specialty 2022",
    author: "Zeal Vora",
    image: "https://img-b.udemycdn.com/course/240x135/1102458_d6e6_2.jpg",
    price: "269.99",
    rating: 4.6,
    people: "5,326",
    category: "aws certification",
    bestseller: true,
  },
  {
    id: 26,
    link: "",
    title: "Art for Kids & Beginners: 15 Easy Drawing & Painting Lessons",
    author: "Em Winn",
    image: "https://img-b.udemycdn.com/course/240x135/670050_69ff_3.jpg",
    price: "1,199.99",
    rating: 4.8,
    people: "740",
    category: "drawing",
    bestseller: false,
    learnings: [
      "Create 15 Magnificent Watercolor Animal Paintings.",
      "Apply the knowledge gained in this course to create unique masterpieces.",
      "Participate in an activity that cultivates critical thinking skills, develops hand-eye coordination, and encourages self-expression.",
      "Build self confidence while having fun!",
    ],
    requirements: [
      "Students will need a computer, tablet, or smart phone, and an internet connection.",
      "Materials and Supplies needed for this course are listed in the Course Description.",
      "Bring it: A desire to create some delightful works of art!",
    ],
    content: [
      [
        [
          "Introduction, Course Goals, Examples of Projects, and Supplies Needed",
        ],
        [
          "Introduction to this Course",
          "Supplies and Materials Needed for This Course (Video)",
          "Supplies and Materials Needed for This Course (Document)",
        ],
      ],
      [
        ["Draw and Paint a Night Owl"],
        [
          "Introduction and Supplies Needed for This Project",
          "Step 1: Draw the Owl",
          "Step 2: Watercolor Paint the Owl",
        ],
      ],
      [
        ["Draw and Watercolor Paint a Shark"],
        [
          "Introduction and Supplies Needed for This Project",
          "Step 1: Draw the Shark",
          "Step 2: Paint the Shark",
        ],
      ],
      [
        ["Draw and Paint a Fish"],
        [
          "Introduction and Supplies Needed for This Project",
          "Step 1: Draw the Fish",
          "Step 2: Paint the Fish",
        ],
      ],
      [
        ["Draw and Paint a Dog"],
        [
          "Introduction and Supplies Needed for This Project",
          "Step 1: Draw a Dog",
          "Step 2: Paint the Dog",
        ],
      ],
      [
        ["Draw and Paint a Frog"],
        [
          "Introduction and Supplies Needed for This Project",
          "Step 1: Draw a Frog",
          "Step 2: Paint the Frog",
        ],
      ],
      [
        ["Draw and Paint a Dragonfly"],
        [
          "Introduction and Supplies Needed for This Project",
          "Step 1: Draw a Dragonfly",
          "Step 2: Paint the Dragonfly",
        ],
      ],
      [
        ["Draw and Paint a Rooster"],
        [
          "Introduction and Supplies Needed for This Project",
          "Step 1: Draw a Rooster",
          "Step 2: Paint the Rooster",
        ],
      ],
      [
        ["Draw and Paint a Fox"],
        [
          "Introduction and Supplies Needed for This Project",
          "Step 1: Draw a Fox",
          "Step 2: Paint the Fox",
        ],
      ],
      [
        ["Draw and Paint an Elephant"],
        [
          "Introduction and Supplies Needed for This Project",
          "Step 1: Draw an Elephant",
          "Step 2: Paint the Elephant",
        ],
      ],
      [
        ["Draw and Paint a Tiger Cat"],
        [
          "Introduction and Supplies Needed for This Project",
          "Step 1: Draw a Cat",
          "Step 2: Paint the Cat",
        ],
      ],
      [
        ["Draw and Paint a Horse"],
        [
          "Introduction to This Project and Supplies Needed",
          "Step 1: Draw a Horse",
          "Step 2: Watercolor Paint the Horse and the Background",
        ],
      ],
      [
        ["Draw and Paint a Butterfly"],
        [
          "Introduction to This Project and Supplies Needed",
          "Step 1: Draw a Butterfly Design",
          "Step 2: Paint the Background",
          "Step 3: Paint the Butterfly",
          "Step 4: Paint the Flowers",
        ],
      ],
      [
        ["Bonus Project: Draw and Paint a Koala"],
        [
          "Introduction to This Project and Supplies Needed",
          "Step 1: Draw a Koala Design",
          "Step 2: Paint the Background",
          "Step 3: Paint the Koala and Details",
        ],
      ],
      [
        ["Bonus Project: Draw and Paint a Moon Cat"],
        [
          "Introduction to This Project and Supplies Needed",
          "Step 1: Draw a Cat Design",
          "Step 2: Paint the Background",
          "Step 3: Paint the Cat",
        ],
      ],
      [
        ["Bonus Project: Draw and Paint a Porcupine in a Cozy Sweater"],
        [
          "Introduction to This Project and Supplies Needed",
          "Pattern Reference Sheet to Use for Ideas",
          "Step 1: Draw a Porcupine Design",
          "Step 2: Paint the Porcupine Design",
        ],
      ],
      [
        ["Thank You for Enrolling in This Course :)"],
        ["Thank You for Enrolling in This Course :)"],
      ],
    ],
  },
  {
    id: 27,
    link: "",
    title: "Financial Budgeting and Forecasting In Excel Complete Course",
    author: "Todd McLeod",
    image: "https://img-b.udemycdn.com/course/240x135/130298_9a8e_10.jpg",
    price: "269.99",
    rating: 4.3,
    people: "3,534",
    category: "excel",
    bestseller: false,
  },
];
