export default [
  {
    id: 1,
    link: "https://www.udemy.com/course/pythonforbeginners/",
    title: "Learn Python: The Complete Python Programming Course",
    description:
      "Learn A-Z everything about Python, from the basics, to advanced topics like Python GUI, Python Data Analysis, and more!",
    author: "Avinash Jain,The Codex",
    image: "https://img-c.udemycdn.com/course/240x135/394676_ce3d_5.jpg",
    price: "679.99",
    rating: 4.4,
    people: "2,948",
    category: "python",
    bestseller: false,
    learnings: [
      "Create their own Python Programs",
      "Become an experienced Python Programmer",
      "Parse the Web and Create their own Games",
    ],
    content: [
      [["Up and Running With Python"], ["Installing Python", "Hello World"]],
      [
        ["The Basics (Data Types)"],
        [
          "Variables",
          "Multiple Assignment",
          "Data Types and Ints",
          "Strings",
          "Placeholders",
          "List/Arrays",
          "List Functions",
          "Dictionaries",
          "Dictionary Functions",
          "Tuples",
        ],
      ],
      [
        ["Conditions and Loops"],
        [
          "If-Else Statements",
          "Relational Operators",
          "Nested If/Else",
          "Elif Statements",
          "Logical Operators",
          "For Loops",
          "While Loops",
          "Nested For Loops",
          "Pass, Break and Continue",
          "Try and Except",
          "Commenting",
          "Quick Tips",
        ],
      ],
      [
        ["Functions!"],
        [
          "Creating your own Functions",
          "Global and Local Vars",
          "Abs and Bool",
          "Help and Dir",
          "Eval and Exec",
          "Str, Int, Float",
          "Recap and Sum",
        ],
      ],
      [
        ["Classes! (Object Orientated Programming)"],
        [
          "Basics of Classes",
          "Functions in Classes",
          "Class Attributes",
          "Inheritance",
          "Overriding Methods",
        ],
      ],
      [
        ["File Input/Output"],
        [
          "Creating a File",
          "Reading a File",
          "Writing to a File",
          "Appending to Files",
          "Copying Files",
        ],
      ],
    ],
  },
  {
    id: 2,
    link: "https://www.udemy.com/course/learning-python-for-data-analysis-and-visualization/",
    title: "Learning Python for Data Analysis and Visualization",
    description:
      "Learn python and how to use it to analyze,visualize and present data. Includes tons of sample code and hours of video!",
    author: "Jose Portilla",
    image: "https://img-c.udemycdn.com/course/240x135/396876_cc92_7.jpg",
    price: "1,599.99",
    rating: 4.4,
    people: "1,019",
    category: "python",
    bestseller: true,
    learnings: [
      "Have an intermediate skill level of Python programming.",
      "Use the Jupyter Notebook Environment.",
      "Use the numpy library to create and manipulate arrays.",
      "Use the pandas module with Python to create and structure data.",
      "Learn how to work with various data formats within python, including: JSON,HTML, and MS Excel Worksheets.",
      "Create data visualizations using matplotlib and the seaborn modules with python.",
      "Have a portfolio of various data analysis projects.",
    ],
    content: [
      [
        ["Programming fundamentals"],
        [
          "Introduction",
          "What is programming?",
          "What is source code?",
          "Compile VS Interpreted Languages",
          "Strings and numbers",
          "Variables",
          "Lists, Arrays or Collections",
          "Conditional Code - If statements",
          "Loops",
          "Functions",
        ],
      ],
      [
        ["Getting Started with Python"],
        [
          "intro to getting started",
          "What is Python?",
          "Installing Python",
          "Running Python IDLE and online",
          "Installing IDE",
        ],
      ],
      [
        ["Python Basics"],
        [
          "Intro to python basics",
          "Exercise files",
          "Strings  &amp; print function",
          "Numbers / Math",
          "Variables",
          "Lists",
          "Tuples",
          "Dictionaries",
        ],
      ],
      [
        ["Conditional structures"],
        [
          "intro to conditional code",
          "If Statements",
          "While Loop",
          "For loop",
          "Break and Continue",
        ],
      ],
      [
        ["Functions"],
        [
          "intro to functions",
          "Custom Functions &amp; arguments",
          "Functions with arguments",
          "Function variable scopes",
          "Function return",
          "Functions with flexible arguments",
          "Unpacking",
          "Modules",
          "Built in functions",
        ],
      ],
      [
        ["Working with files"],
        [
          "Intro to working files",
          "Opening / Creating files / Writing files",
          "File reading",
          "Renaming files",
          "Deleting files",
        ],
      ],
    ],
  },
  {
    id: 3,
    link: "https://www.udemy.com/course/python-for-beginners-learn-programming-from-scratch/",
    title: "Python for Beginners - Learn Programming from scratch",
    description:
      "Learn python and how to use it to analyze,visualize and present data. Includes tons of sample code and hours of video!",
    author: "Edwin Diaz, Coding Facutly Solutions",
    image: "https://img-c.udemycdn.com/course/240x135/405878_e5a0_3.jpg",
    price: "679.99",
    rating: 4.4,
    people: "1,781",
    category: "python",
    bestseller: false,
    learnings: [
      "To learn the python language",
      "To learn the CORE skills to understand any programming language",
    ],
    content:[[["Programming fundamentals"], ["Introduction", "What is programming?", "What is source code?", "Compile VS Interpreted Languages", "Strings and numbers", "Variables", "Lists, Arrays or Collections", "Conditional Code - If statements", "Loops", "Functions"]], [["Getting Started with Python"], ["intro to getting started", "What is Python?", "Installing Python", "Running Python IDLE and online", "Installing IDE"]], [["Python Basics"], ["Intro to python basics", "Exercise files", "Strings  &amp; print function", "Numbers / Math", "Variables", "Lists", "Tuples", "Dictionaries"]], [["Conditional structures"], ["intro to conditional code", "If Statements", "While Loop", "For loop", "Break and Continue"]], [["Functions"], ["intro to functions", "Custom Functions &amp; arguments", "Functions with arguments", "Function variable scopes", "Function return", "Functions with flexible arguments", "Unpacking", "Modules", "Built in functions"]], [["Working with files"], ["Intro to working files", "Opening / Creating files / Writing files", "File reading", "Renaming files", "Deleting files"]]]

  },
  {
    id: 4,
    link: "https://www.udemy.com/course/learn-python/",
    title: "Learn Python: Python for Beginners",
    description:
      "Learn python and how to use it to analyze,visualize and present data. Includes tons of sample code and hours of video!",
    author: "Abrar Hussain",
    image: "https://img-c.udemycdn.com/course/240x135/426570_1b91_3.jpg",
    price: "319.99",
    rating: 4.3,
    people: "21,773",
    category: "python",
    bestseller: false,
  },
  {
    id: 5,
    link: "https://www.udemy.com/course/python-beyond-the-basics-object-oriented-programming/",
    title: "Python Beyond the Basics - Object-Oriented Programming",
    description:
      "Learn python and how to use it to analyze,visualize and present data. Includes tons of sample code and hours of video!",
    author: "Infinite Skills",
    image: "https://img-c.udemycdn.com/course/480x270/449532_2aa9_7.jpg",
    price: "519.99",
    rating: 4.4,
    people: "2,930",
    category: "python",
    bestseller: false,
  },
  {
    id: 6,
    link: "https://www.udemy.com/course/selenium-webdriver-and-python/",
    title: "Python From Scratch & Selenium WebDriver QA Automation 2022",
    description:
      "Learn python and how to use it to analyze,visualize and present data. Includes tons of sample code and hours of video!",
    author: "Admas Kinfu",
    image: "https://img-c.udemycdn.com/course/480x270/482754_7146_6.jpg",
    price: "1,299.99",
    rating: 4.7,
    people: "1,813",
    category: "python",
    bestseller: true,
  },
  {
    id: 7,
    link: "https://www.udemy.com/course/teach-your-kids-to-code/",
    title: "Teach Your Kids to Code: Learn to Program Python at Any Age!",
    description:
      "Learn python and how to use it to analyze,visualize and present data. Includes tons of sample code and hours of video!",
    author: "Bryson Payne",
    image: "https://img-c.udemycdn.com/course/480x270/519554_da68_6.jpg",
    price: "319.99",
    rating: 4.5,
    people: "18,809",
    category: "python",
    bestseller: true,
  },
  {
    id: 8,
    link: "https://www.udemy.com/course/python-for-data-structures-algorithms-and-interviews/",
    title: "Python for Data Structures, Algorithms, and Interviews!",
    description:
      "Learn python and how to use it to analyze,visualize and present data. Includes tons of sample code and hours of video!",
    author: "Jose Portilla",
    image: "https://img-c.udemycdn.com/course/480x270/535622_3bc0.jpg",
    price: "1,299.99",
    rating: 4.5,
    people: "10.701",
    category: "python",
    bestseller: false,
  },
  {
    id: 9,
    link: "https://www.udemy.com/course/automate/",
    title: "Automate the Boring Stuff with Python Programming",
    description:
      "Learn python and how to use it to analyze,visualize and present data. Includes tons of sample code and hours of video!",
    author: "Al Sweigart",
    image: "https://img-c.udemycdn.com/course/480x270/543600_64d1_4.jpg",
    price: "269.99",
    rating: 4.7,
    people: "10,703",
    category: "python",
    bestseller: false,
  },
  {
    id: 10,
    link: "https://www.udemy.com/course/complete-python-bootcamp/",
    title: "2022 Complete Python Bootcamp From Zero to Hero in Python",
    description:
      "Learn python and how to use it to analyze,visualize and present data. Includes tons of sample code and hours of video!",
    author: "Jose Portilla",
    image: "https://img-c.udemycdn.com/course/480x270/567828_67d0.jpg",
    price: "299.99",
    rating: 4.5,
    people: "10,693",
    category: "python",
    bestseller: false,
  },
  {
    id: 11,
    link: "https://www.udemy.com/course/complete-python-bootcamp/",
    title: "Become a Certified HTML, CSS, JavaScript Web Developer",
    author: "Mark Lassoff",
    image: "https://img-b.udemycdn.com/course/240x135/11475_9dac_14.jpg",
    price: "679.99",
    rating: 4.5,
    people: "2,734",
    category: "web development",
    bestseller: false,
  },
  {
    id: 12,
    link: "https://www.udemy.com/course/complete-python-bootcamp/",
    title: "The Complete 2020 Fullstack Web Developer Course",
    author: "Kalob Taulien",
    image: "https://img-b.udemycdn.com/course/240x135/19332_6b49_15.jpg",
    price: "1,299.99",
    rating: 4.5,
    people: "6,153",
    category: "web development",
    bestseller: false,
    content:[[["Before We Begin"], ["Course Perks and File Downloads", "How to ask great questions"]], [["The Ultimate HTML Developer: Introduction"], ["Welcome to The Ultimate HTML Developer Modules", "Introduction", "What is HTML?", "Project Files"]], [["The Ultimate HTML Developer: Getting Started"], ["Getting Started", "Code Editing Programs", "Browsers", "Elements", "Hello World!", "Page/Tab Titles", "Doctypes", "Attributes", "Headers", "Line Breaks", "Bold vs. Strong", "Italics vs. Emphasis", "Underline", "Code Comments", "Links", "Internal Links", "Relative Links", "Images", "Block Elements vs. Inline Elements", "Div Elements", "Lists", "Introduction to Tables, Rows and Cells", "Tables: Merging Cells and Columns", "Module Summary"]], [["The Ultimate HTML Developer: Advanced HTML"], ["The DOM", "Introduction to XHTML", "Inline CSS", "CSS Crash Course &amp; Internal CSS", "External CSS &amp; CSS Files", "Code Formatting", "Bold &amp; Italic Semantics", "Head Elements", "Meta Tags", "Asset Pathing", "Favicons", "HTML Entities", "Introduction to Forms", "Input Elements", "Textarea", "Buttons", "Dropdown Menus", "New HTML5 Semantic Tags", "Videos", "Music/Audio", "Introduction to Responsive Web Design"]], [["The Ultimate HTML Developer: Your Project"], ["Your Project, Part 1", "Your Project, Part 2", "The Ultimate HTML Developer: Summary"]], [["CSS &amp; CSS3 Masterclass: Introduction"], ["Welcome to the CSS &amp; CSS3 Masterclass!", "CSS Introduction", "Syntax Introduction", "Editors", "CSS Masterclass e-book (free)", "What is Inline CSS?", "What is Internal CSS?", "What is External CSS?"]], [["CSS &amp; CSS3 Masterclass: Getting Started"], ["Color Types", "Background Colors", "Background Images", "Repeating Background Images", "Borders", "The Box Model (Extremely Important!)", "Padding", "Margin", "Centering an Element", "Outline", "Cursor", "Mini Project", "Mini Project: Solution"]], [["CSS &amp; CSS3 Masterclass: Text Formatting"], ["Text Color", "Text Alignment", "Text Decoration", "Text Transform", "Text Indent", "Letter Spacing", "Line Height", "Direction", "Word Spacing"]], [["CSS &amp; CSS3 Masterclass: Fonts and Font Styling"], ["Serif vs. Sans Serif", "Font Family", "Lots of Free Fonts", "Font Style", "Font Size", "Font Weight", "Font Variant", "Font Awesome Icons"]], [["CSS &amp; CSS3 Masterclass: Links and their \"states\""], ["Links Introduction", "Hover Over Links", "Visited Links", "Active Links"]]]

  },
  {
    id: 13,
    link: "https://www.udemy.com/course/complete-python-bootcamp/",
    title: "Introduction to Web Development",
    author: "Mark Lassoff",
    image: "https://img-b.udemycdn.com/course/240x135/99986_6cb4_10.jpg",
    price: "229.99",
    rating: 4.3,
    people: "1,734",
    category: "web development",
    bestseller: true,
  },
  {
    id: 14,
    link: "",
    title: "Become a Certified HTML, CSS, JavaScript Web Developer",
    author: "Evan Kimbrell",
    image: "https://img-b.udemycdn.com/course/240x135/369662_7246_2.jpg",
    price: "679.99",
    rating: 4.6,
    people: "1,534",
    category: "web development",
    bestseller: true,
  },
  {
    id: 15,
    link: "https://www.udemy.com/course/complete-python-bootcamp/",
    title: "Microsoft Excel 2013 Course Beginners/ Intermediate Training",
    author: "Infinite Skills",
    image: "https://img-b.udemycdn.com/course/240x135/31535_e351_7.jpg",
    price: "519.99",
    rating: 4.6,
    people: "1,153",
    category: "excel",
    bestseller: false,
  },
  {
    id: 16,
    link: "https://www.udemy.com/course/complete-python-bootcamp/",
    title: "Microsoft Excel 2013 Advanced. Online Excel Training Course",
    author: "Infinite Skills",
    image: "https://img-b.udemycdn.com/course/240x135/39292_b3f3_9.jpg",
    price: "519.99",
    rating: 4.5,
    people: "3,534",
    category: "excel",
    bestseller: false,
  },
  {
    id: 17,
    link: "",
    title: "Microsoft Excel - From Beginner to Expert in 6 Hours",
    author: "Todd McLeod",
    image: "https://img-b.udemycdn.com/course/240x135/49250_a658_8.jpg",
    price: "269.99",
    rating: 4.6,
    people: "24,534",
    category: "excel",
    bestseller: true,
  },
  {
    id: 18,
    link: "https://www.udemy.com/course/automate/",
    title: "The Complete JavaScript Course 2022: From Zero to Expert!",
    author: "Jonas Schmedtmann",
    image: "https://img-b.udemycdn.com/course/240x135/851712_fc61_6.jpg",
    price: "1699.99",
    rating: 4.8,
    people: "97,703",
    category: "java script",
    bestseller: true,
  },
  {
    id: 19,
    link: "https://www.udemy.com/course/complete-python-bootcamp/",
    title: "1 Hour JavaScript",
    author: "John Bura",
    image: "https://img-b.udemycdn.com/course/240x135/63612_8797_4.jpg",
    price: "299.99",
    rating: 4.4,
    people: "1,893",
    category: "java script",
    bestseller: false,
  },
  {
    id: 20,
    link: "https://www.udemy.com/course/complete-python-bootcamp/",
    title: "Javascript for Beginners",
    author: "Tech learning Network",
    image: "https://img-b.udemycdn.com/course/240x135/8324_fa84_13.jpg",
    price: "179.99",
    rating: 4.5,
    people: "734",
    category: "java script",
    bestseller: false,
  },
  {
    id: 21,
    link: "https://www.udemy.com/course/complete-python-bootcamp/",
    title: "JavaScript from Beginner to Expert",
    author: "Arkadiusz Włodarczyk",
    image: "https://img-b.udemycdn.com/course/240x135/426196_3cb8_4.jpg",
    price: "829.99",
    rating: 4.5,
    people: "1,153",
    category: "java script",
    bestseller: false,
  },
  {
    id: 22,
    link: "https://www.udemy.com/course/complete-python-bootcamp/",
    title: "ES6 Javascript: The Complete Developer's Guide",
    author: "Stephan Grider",
    image: "https://img-b.udemycdn.com/course/240x135/861624_864d_2.jpg",
    price: "619.99",
    rating: 4.7,
    people: "12,089",
    category: "java script",
    bestseller: true,
  },
  {
    id: 23,
    link: "",
    title: "Learning Data Structures in JavaScript from Scratch",
    author: "Eric Traub",
    image: "https://img-b.udemycdn.com/course/240x135/973918_93b1_2.jpg",
    price: "1,199.99",
    rating: 4.8,
    people: "2,071",
    category: "java script",
    bestseller: false,
  },
  {
    id: 24,
    link: "",
    title: "Data Science and Machine Learning Bootcamp with R",
    author: "Jose Portilla",
    image: "https://img-b.udemycdn.com/course/240x135/821726_8071.jpg",
    price: "1,599.99",
    rating: 4.8,
    people: "15,071",
    category: "data science",
    bestseller: false,
  },
  {
    id: 25,
    link: "",
    title: "AWS Certified Security Specialty 2022",
    author: "Zeal Vora",
    image: "https://img-b.udemycdn.com/course/240x135/1102458_d6e6_2.jpg",
    price: "269.99",
    rating: 4.6,
    people: "5,326",
    category: "aws certification",
    bestseller: true,
  },
  {
    id: 26,
    link: "",
    title: "Art for Kids & Beginners: 15 Easy Drawing & Painting Lessons",
    author: "Em Winn",
    image: "https://img-b.udemycdn.com/course/240x135/670050_69ff_3.jpg",
    price: "1,199.99",
    rating: 4.8,
    people: "740",
    category: "drawing",
    bestseller: false,
    content:[[["Introduction, Course Goals, Examples of Projects, and Supplies Needed"], ["Introduction to this Course", "Supplies and Materials Needed for This Course (Video)", "Supplies and Materials Needed for This Course (Document)"]], [["Draw and Paint a Night Owl"], ["Introduction and Supplies Needed for This Project", "Step 1: Draw the Owl", "Step 2: Watercolor Paint the Owl"]], [["Draw and Watercolor Paint a Shark"], ["Introduction and Supplies Needed for This Project", "Step 1: Draw the Shark", "Step 2: Paint the Shark"]], [["Draw and Paint a Fish"], ["Introduction and Supplies Needed for This Project", "Step 1: Draw the Fish", "Step 2: Paint the Fish"]], [["Draw and Paint a Dog"], ["Introduction and Supplies Needed for This Project", "Step 1: Draw a Dog", "Step 2: Paint the Dog"]], [["Draw and Paint a Frog"], ["Introduction and Supplies Needed for This Project", "Step 1: Draw a Frog", "Step 2: Paint the Frog"]], [["Draw and Paint a Dragonfly"], ["Introduction and Supplies Needed for This Project", "Step 1: Draw a Dragonfly", "Step 2: Paint the Dragonfly"]], [["Draw and Paint a Rooster"], ["Introduction and Supplies Needed for This Project", "Step 1: Draw a Rooster", "Step 2: Paint the Rooster"]], [["Draw and Paint a Fox"], ["Introduction and Supplies Needed for This Project", "Step 1: Draw a Fox", "Step 2: Paint the Fox"]], [["Draw and Paint an Elephant"], ["Introduction and Supplies Needed for This Project", "Step 1: Draw an Elephant", "Step 2: Paint the Elephant"]]]

  },
  {
    id: 27,
    link: "",
    title: "Financial Budgeting and Forecasting In Excel Complete Course",
    author: "Todd McLeod",
    image: "https://img-b.udemycdn.com/course/240x135/130298_9a8e_10.jpg",
    price: "269.99",
    rating: 4.3,
    people: "3,534",
    category: "excel",
    bestseller: false,
  },
];
