export default [
  {
    id: 1,
    photo: "https://img-c.udemycdn.com/user/200_H/10260436_946b_6.jpg",
    title: "CEO of TheCodex.me - Teaching 500,000+ Students how to code",
    name: "Avinash Jain",
    rating: 4.4,
    students: "891,073",
    about: [
      "Avinash Jain is currently a senior at UC Berkeley majoring in Electrical Engineering and Computer Science. He's the CEO and Founder of TheCodex, an online educational platform focused on bringing the best programming content to hundreds of thousands of students around the world.",
      "His programming journey began at the age of 10, starting off with simple Python scripts to crawl the weather. Since then, he's worked at numerous companies and is professionally experienced in Python, iOS Development and Web Development. He's launched a plethora of applications in the App Store amassing thousands of downloads. Additionaly, he's competed and won in several hackathons around the world including PennApps and NWHacks.",
      "Avinash has a passion to teach - his enthusiasm and love for programming is evident in every video. For the past 7 years he's been an instructor on Udemy and he loves motivating and enabling others to pursue their programming dreams. He hopes to help students realize the power of programming and jumpstart their careers through his courses.",
      "Checkout TheCodex for all of his courses, fantastic discounts, and any guidance or help.",
    ],
    courses: 16,
    reviews: "73,790",
  },
  {
    id: 2,
    photo: "https://img-b.udemycdn.com/user/200_H/9685726_67e7_4.jpg",
    title: "Head of Data Science at Pierian Training",
    name: "Jose Portilla",
    rating: 4.6,
    students: "3,006,323",
    about: [
      "Jose Marcial Portilla has a BS and MS in Mechanical Engineering from Santa Clara University and years of experience as a professional instructor and trainer for Data Science, Machine Learning and Python Programming. He has publications and patents in various fields such as microfluidics, materials science, and data science. Over the course of his career he has developed a skill set in analyzing data and he hopes to use his experience in teaching and data science to help other people learn the power of programming, the ability to analyze data, and the skills needed to present the data in clear and beautiful visualizations. Currently he works as the Head of Data Science for Pierian Training and provides in-person data science and python programming training courses to employees working at top companies, including General Electric, Cigna, The New York Times, Credit Suisse, McKinsey and many more. Feel free to check out the website link to find out more information about training offerings.",
    ],
    courses: 54,
    reviews: "938,439",
  },
  {
    id: 3,
    photo: "https://img-b.udemycdn.com/user/200_H/6772884_fcfc_2.jpg",
    title: "Web Developer & Premium Instructor - 800,000 students",
    name: "Edwin Diaz",
    rating: 4.4,
    students: "828,487",
    about: [
      "Edwin Diaz is a software and web technologies engineer, a life coach trainer who is also a serial entrepreneur with multiple online businesses, ranging from online jewelry shops, affiliate websites, application development and consultations services, personal online schools, etc.",
      "With over one million students, and clients growing by the thousands a day, Mr. Diaz lets the numbers speak for themselves.",
      "Founding multiple online companies have allowed Mr. Diaz to have the time to teach others. He currently teaches web technologies on different online platforms. He also teaches life coaching sessions to help others achieve a high level of success in many areas of life.",
      "For Mr. Diaz, there is nothing more rewarding than helping others become successful.",
      'His ability to transmit energy, enthusiasm, and complex knowledge allows him to do what he does best "Teach".',
      "Teaching is not just a job for Mr. Diaz but a way of life that continues to flourish every single day.",
      "Apart from teaching he enjoys spending part of his time with his family.",
    ],
    courses: 47,
    reviews: "123,267",
  },
  {
    id: 4,
    photo: "https://img-b.udemycdn.com/user/200_H/9100824_a767_2.jpg",
    title: "Teacher, Art Instructor, Artist",
    name: "Em Winn",
    rating: 4.6,
    students: "121,487",
    about: [
      "Hi. My name is Em Winn and teaching art to children is what I love to do! I pride myself on creating dynamic, meaningful, and engaging art lessons that are taught in a relaxing and joyful way. I have over 20 years teaching experience in the elementary classroom and in the art studio, and I feel that I have a good grasp on how to create an environment that makes kids feel happy, motivated, confident, and successful. Let the creative fun begin!",
    ],
    courses: 23,
    reviews: "13,267",
  },
  {
    id: 5,
    photo: "https://img-b.udemycdn.com/user/200_H/22632534_6ae1.jpg",
    title: "Programming Instructor with over 500,000 students worldwide.",
    name: "Mark Lassoff",
    rating: 4.4,
    students: "92,076",
    about: [
      "Mark Lassoff 's parents frequently claim that Mark was born to be a programmer.  Starting, in the mid-eighties at age 11, Mark was hard at work on his Commodore 64 writing games in the BASIC language.  After completing a computer science degree, Mark developed software for several well-known internet startups during the initial internet boom of the mid 1990’s.  Five years ago Mark parlayed a two decades of software development experience into his latest entrepreneurial venture, LearnToProgram Media.",
      "LearnToProgram Media publishes online courses that teach mobile, web, and game development. Over 500,000 people have learned programming from Mark through online classes he has either authored or published. In addition to publishing popular courses and books LearnToProgram Media operates an internet video network which produces several programs on software development.",
      "Previously Mark founded PowerPlant Marketing, which created marketing automation software for REALTORS™.  After the sale of PowerPlant, Mark went on to found Internet Broadcasting Group which counted among it’s launch clients Nike, Blue Moon Brewing Company and Opubco.",
      "Mark lives in Connecticut and speaks worldwide on software development, entrepreneurship and online learning.  He has spoken at TechWeek NY, TechWeek LA, and SXSW, among other large conferences.  In his spare time he he enjoys aviation, mentoring new business owners and spending time with life-long friends and family.",
    ],
    courses: 25,
    reviews: "9,167",
  },
];
