export default {
  courses: [
    {
      id: 1,
      link: "https://www.udemy.com/course/pythonforbeginners/",
      title: "Learn Python: The Complete Python Programming Course",
      instructor: 1,
      description:
        "Learn A-Z everything about Python, from the basics, to advanced topics like Python GUI, Python Data Analysis, and more!",
      author: "Avinash Jain,The Codex",
      image: "https://img-c.udemycdn.com/course/240x135/394676_ce3d_5.jpg",
      price: "679.99",
      rating: 4.5,
      people: "2,948",
      category: "python",
      bestseller: true,
      ratingsSplit: [43, 37, 15, 3, 2],
      hours:"14.5 total hours • AllLevels • Subtitles",
      learnings: [
        "Create their own Python Programs",
        "Become an experienced Python Programmer",
        "Parse the Web and Create their own Games",
      ],
      requirements: [
        "Macintosh (OSX)/ Windows(Vista and higher) Machine",
        "Internet Connection",
      ],
      descriptionDetailed: [
        "Do you want to become a programmer? Do you want to learn how to create games, automate your browser, visualize data, and much more? ",
        "If you’re looking to learn Python for the very first time or need a quick brush-up, this is the course for you!",
        "Python has rapidly become one of the most popular programming languages around the world. Compared to other languages such as Java or C++, Python consistently outranks and outperforms these languages in demand from businesses and job availability. The average Python developer makes over $100,000 - this number is only going to grow in the coming years.",
        "If you read the above list and are feeling a bit confused, don’t worry! As an instructor and student on Udemy for almost 4 years, I know what it’s like to be overwhelmed with boring and mundane. I promise you’ll have a blast learning the ins and outs of python. I’ve successfully taught over 200,000+ students from over 200 countries jumpstart their programming journeys through my courses.",
        "So what are you waiting for? Jumpstart your programming journey and dive into the world of Python by enrolling in this course today!",
      ],
      whoIsThisFor: [
        "Even if you haven't touched coding before, it won't matter. The easy step-to-step lectures will quickly guide you through everything you'll need to know about coding, mainly Python. This course is here for you to get accustomed and familiar with Python and its syntax. And above all, Python is one of the easiest coding languages to learn, and there's a lot you can do with it.",
      ],
      content: [
        [["Up and Running With Python"], ["Installing Python", "Hello World"]],
        [
          ["The Basics (Data Types)"],
          [
            "Variables",
            "Multiple Assignment",
            "Data Types and Ints",
            "Strings",
            "Placeholders",
            "Lists/Arrays",
            "List Functions",
            "Dictionaries",
            "Dictionary Functions",
            "Tuples",
            "Exercise Files",
          ],
        ],
        [
          ["Conditions and Loops"],
          [
            "If-Else Statements",
            "Relational Operators",
            "Nested If/Else",
            "Elif Statements",
            "Logical Operators",
            "For Loops",
            "While Loops",
            "Nested For Loops",
            "Pass, Break and Continue",
            "Try and Except",
            "Commenting",
            "Quick Tips",
            "Exercise Files",
          ],
        ],
        [
          ["Functions!"],
          [
            "Creating our own Functions",
            "Global and Local Vars",
            "Abs and Bool",
            "Help and Dir",
            "Eval and Exec",
            "Str, Int, Float",
            "Recap and Sum",
          ],
        ],
        [
          ["Classes! (Object Orientated Programming)"],
          [
            "Basics of Classes",
            "Functions in Classes",
            "Class Attributes",
            "Inheritance",
            "Overriding Methods",
          ],
        ],
        [
          ["File Input/Output"],
          [
            "Creating a File",
            "Creating a File (Windows)",
            "Reading a File",
            "Writing to a File",
            "Appending to Files",
            "Copying Files",
          ],
        ],
        [
          ["Using Python Modules"],
          [
            "Random Module - Randint",
            "Guessing Game",
            "Guessing Game Challenge",
            "Random Module - Shuffle and Choice",
            "Sys Module",
            "Time Module",
            "Turtle Module",
            "For Loops in Turtle",
            "Up and Down Functions",
            "Coloring in Turtle",
            "Functions in Turtle",
            "Exercise Files",
          ],
        ],
        [
          ["Crawling The Web"],
          [
            "Re Module",
            "Crawling The Web (Stocks)",
            "Stock Quotes (.py)",
            "Crawling The Web (Weather)",
            "Weather (.py)",
            "Crawling The Web (Definition)",
            "Definition (.py)",
          ],
        ],
        [
          ["Beautiful Soup HTML Parsing"],
          [
            "Intro to Beautiful Soup",
            "Installing the Beautiful Soup Module",
            "Prettify with Soup",
            "Drilling Down",
            "Functions in Soup",
            ".String and .Parent",
            "Searching in Soup",
            "Weather Parsing",
            "Antonym Parsing",
          ],
        ],
        [
          ["MatPlotLib - Charts, Plots and 3D Figures!"],
          [
            "Intro to MatPlotLib",
            "First Graph!",
            "Understanding the MatPlotLib Interface",
            "Graph Labels",
            "Creating a Graph from a File",
            "Understanding SubPlots and Figures",
            "Coloring of Graph",
            "Multiple Plots in a Graph",
            "Multiple Graphs in a Figure",
            "What about 3 graphs?",
            "Bar Graphs Intro",
            "Modifying our Bar Graph",
            "Pie Chart Intro",
            "Modifying our Pie Chart",
            "Adding a Legend",
            "3D Graphics Intro",
            "3D Scatter Plots",
            "Multiple 3D Scatter Plots",
            "3D Bar Graphs",
            "3D Wireframes",
          ],
        ],
        [
          ["Data Analysis with Pandas!"],
          [
            "Intro to Pandas",
            "Series Data Structure",
            "Series Continuation",
            "Data Frames Intro",
            "Creating a CSV",
            "Reading a CSV",
            "Writing to a CSV",
            "Getting our Data",
            "Slicing Data Frames",
            "Data Manipulation",
            "Indexing and More",
            "Merging Data Frames",
            "GroupBy Function",
            "MovieLens Data",
            "Heavy Data Analysis",
            "MatPlotLib with Pandas",
            "Let's Finish This",
          ],
        ],
        [
          ["Python GUI with Tkinter"],
          [
            "Tkinter Introduction",
            "Labels",
            "Buttons",
            "Layouts",
            "Fill",
            "Grid Layout",
            "Entries",
            "Check Buttons",
            "GUI Login",
            "Actions on Button Click",
            "Binding Functions",
            "More Binding!",
            "Getting Entry Data",
            "Message Box",
            "Drop Down Menus",
            "Calculator Part 1",
            "Calculator Part 2",
            "Calculator Part 3",
            "Calculator Part 4",
            "Canvas Intro",
            "Canvas Objects",
            "Canvas Fill",
            "Random Rectangle Generator",
            "Text and Arcs",
            "Animations",
          ],
        ],
        [
          ["Our First Game (Bounce!)"],
          [
            "Creating our Ball",
            "Adding the Game Interface",
            "Adding the Paddle",
            "Final Touches",
            "Recap",
            "Bounce! (.py) (v1/v2/v3)",
          ],
        ],
        [
          ["Our Second Game (Pong!)"],
          [
            "Creating our Ball",
            "Adding Paddle1",
            "Adding Paddle2",
            "Final Touches",
            "Pong! (.py)",
          ],
        ],
        [["What's Next?"], ["Up and Beyond!"]],
      ],
      reviews: [
        {
          content:
            "The sound is subpar. The majority of the time, I played at MAX volume. Although the content is extremely basic, I learned a lot.\nThank you very much!",
          rating: 3.0,
          created_formatted_with_time_since: "2 weeks ago",
          userTitle: "Jacques Steyn",
          userInitials: "JS",
        },
        {
          content:
            "Sometimes confusing but was able to clarify. Good job nonetheless.",
          rating: 3.0,
          created_formatted_with_time_since: "3 weeks ago",
          userTitle: "Asif H.",
          userInitials: "AH",
        },
        {
          content:
            "In depth concepts of python have been clearly explained. Good chemistry between student and instructor. Fantastic course. Completed every vid and had lot of fun",
          rating: 5,
          created_formatted_with_time_since: "2 months  ago",
          userTitle: "Saurish R.",
          userInitials: "SR",
        },
        {
          content:
            "i can't say as i have not taken that many classes yet but so far it is good.",
          rating: 4,
          created_formatted_with_time_since: "2 weeks ago",
          userTitle: "Shiristi",
          userInitials: "S",
        },
      ],
    },
    {
      id: 2,
      link: "https://www.udemy.com/course/learning-python-for-data-analysis-and-visualization/",
      title: "Learning Python for Data Analysis and Visualization",
      instructor: 2,
      description:
        "Learn python and how to use it to analyze,visualize and present data. Includes tons of sample code and hours of video!",
      author: "Jose Portilla",
      image: "https://img-c.udemycdn.com/course/240x135/396876_cc92_7.jpg",
      price: "1,599.99",
      rating: 4.4,
      people: "1,019",
      category: "python",
      bestseller: true,
      requirements: [
        "Basic math skills.",
        "Basic to Intermediate Python Skills",
        "Have a computer (either Mac, Windows, or Linux)",
        "Desire to learn!",
      ],
      ratingsSplit: [51, 29, 12, 5, 3],
      learnings: [
        "Have an intermediate skill level of Python programming.",
        "Use the Jupyter Notebook Environment.",
        "Use the numpy library to create and manipulate arrays.",
        "Use the pandas module with Python to create and structure data.",
        "Learn how to work with various data formats within python, including: JSON,HTML, and MS Excel Worksheets.",
        "Create data visualizations using matplotlib and the seaborn modules with python.",
        "Have a portfolio of various data analysis projects.",
      ],
      descriptionDetailed: [
        "PLEASE READ BEFORE ENROLLING: ",
        "1.) THERE IS AN UPDATED VERSION OF THIS COURSE: ",
        '"PYTHON FOR DATA SCIENCE AND MACHINE LEARNING BOOTCAMP" ',
        '2.) IF YOU ARE A COMPLETE BEGINNER IN PYTHON-CHECK OUT MY OTHER COURSE "COMPLETE PYTHON MASTERCLASS JOURNEY"! ',
        "",
        "",
        "CLICK ON MY PROFILE TO FIND IT. ",
        "(PLEASE WATCH THE FIRST PROMO VIDEO ON THIS PAGE FOR MORE INFO) ",
        "",
        "",
        "",
        "This course will give you the resources to learn python and effectively use it analyze and visualize data! Start your career in Data Science! ",
        "You'll get a full understanding of how to program with Python and how to use it in conjunction with scientific computing modules and libraries to analyze data.",
        "You will also get lifetime access to over 100 example python code notebooks, new and updated videos, as well as future additions of various data analysis projects that you can use for a portfolio to show future employers!",
        "By the end of this course you will: ",
        "- Have an understanding of how to program in Python.",
        "- Know how to create and manipulate arrays using numpy and Python.",
        "- Know how to use pandas to create and analyze data sets.",
        "- Know how to use matplotlib and seaborn libraries to create beautiful data visualization.",
        "- Have an amazing portfolio of example python data analysis projects!",
        "- Have an understanding of Machine Learning and SciKit Learn!",
        "With 100+ lectures and over 20 hours of information and more than 100 example python code notebooks, you will be excellently prepared for a future in data science!",
      ],
      whoIsThisFor: [
        "Anyone interested in learning more about python, data science, or data visualizations.",
        "Anyone interested about the rapidly expanding world of data science!",
      ],
      reviews: [
        {
          content:
            "His voice in each video can either be audible or barely audible. If it was consistent then it would be fine, but I have to keep adjusting the volume.",
          rating: 2.5,
          created_formatted_with_time_since: "4 weeks ago",
          userTitle: "Bryan P.",
          userInitials: "BP",
        },
        {
          content:
            "Awesome teacher! I'm enjoying the presented course material and learning a lot. Thank you Jose !!!!!",
          rating: 5.0,
          created_formatted_with_time_since: "4 weeks ago",
          userTitle: "Justin M.",
          userInitials: "JM",
        },
        {
          content:
            "Really enjoyed the course, being a total beginner it really set a good foundation.",
          rating: 4.5,
          created_formatted_with_time_since: "5 months  ago",
          userTitle: "Sechaba M.",
          userInitials: "SM",
        },
      ],
      content: [
        [
          ["Programming fundamentals"],
          [
            "Introduction",
            "What is programming?",
            "What is source code?",
            "Compile VS Interpreted Languages",
            "Strings and numbers",
            "Variables",
            "Lists, Arrays or Collections",
            "Conditional Code - If statements",
            "Loops",
            "Functions",
          ],
        ],
        [
          ["Getting Started with Python"],
          [
            "intro to getting started",
            "What is Python?",
            "Installing Python",
            "Running Python IDLE and online",
            "Installing IDE",
          ],
        ],
        [
          ["Python Basics"],
          [
            "Intro to python basics",
            "Exercise files",
            "Strings  &amp; print function",
            "Numbers / Math",
            "Variables",
            "Lists",
            "Tuples",
            "Dictionaries",
          ],
        ],
        [
          ["Conditional structures"],
          [
            "intro to conditional code",
            "If Statements",
            "While Loop",
            "For loop",
            "Break and Continue",
          ],
        ],
        [
          ["Functions"],
          [
            "intro to functions",
            "Custom Functions &amp; arguments",
            "Functions with arguments",
            "Function variable scopes",
            "Function return",
            "Functions with flexible arguments",
            "Unpacking",
            "Modules",
            "Built in functions",
          ],
        ],
        [
          ["Working with files"],
          [
            "Intro to working files",
            "Opening / Creating files / Writing files",
            "File reading",
            "Renaming files",
            "Deleting files",
          ],
        ],
      ],
    },
    {
      id: 26,
      link: "",
      title: "Art for Kids & Beginners: 15 Easy Drawing & Painting Lessons",
      instructor: 4,
      author: "Em Winn",
      image: "https://img-b.udemycdn.com/course/240x135/670050_69ff_3.jpg",
      price: "1,199.99",
      rating: 4.8,
      people: "740",
      category: "drawing",
      bestseller: false,
      ratingsSplit: [60, 28, 7, 3, 2],
      learnings: [
        "Create 15 Magnificent Watercolor Animal Paintings.",
        "Apply the knowledge gained in this course to create unique masterpieces.",
        "Participate in an activity that cultivates critical thinking skills, develops hand-eye coordination, and encourages self-expression.",
        "Build self confidence while having fun!",
      ],
      requirements: [
        "Students will need a computer, tablet, or smart phone, and an internet connection.",
        "Materials and Supplies needed for this course are listed in the Course Description.",
        "Bring it: A desire to create some delightful works of art!",
      ],
      descriptionDetailed: [
        "Do you know a young artist who would enjoy learning how to draw and paint with watercolor paints?  ",
        "Are you looking for an experienced art teacher to guide them throughout the creative process?  ",
        "Are you seeking a healthy activity that will encourage creativity and boost self-confidence?  ",
        "This Drawing and Watercolor Painting course may be just what you are looking for! Designed with beginners in mind, this course is suitable for ALL AGES. With a total of 15 unique drawing and watercolor painting projects, students will learn the skills to create masterpieces of their own long after the course is complete.",
        "The teaching process used for the drawing portion of each project is a step-by-step method that will inspire and delight students into drawing action! This process involves organizing shapes and lines together until a recognizable outcome is achieved.",
        "After students complete the drawing portion of their project, they will move onto painting the project. Young artists will learn basic watercolor techniques and apply these techniques to complete their project. This Drawing and Watercolor Painting course is designed to give beginners the tools they need to begin their artistic journey into self-expression, reflection, and creative thinking.",
        "Supplies and materials needed for this course: ",
        " • watercolor paper",
        " • watercolor paints",
        " • paintbrushes",
        " • crayons or oil pastels",
        " • paper towels",
        " • bowl of water",
        " • mat to protect work area",
        "**This course was updated 6/2022! ",
        "Please Note: ",
        "This course is intended to be purchased by a parent or guardian for use by a beginner artist or novice art student. Adult supervision is recommended. Per Udemy’s Policy: Those under 18 may use the services only if a parent or guardian opens their account, handles any enrollments, and manages their account usage.",
        "I would love to hear from you. ",
        "Please let me know if you have questions, comments, or suggestions. I am here to help :)",
        "About the Instructor: ",
        "My name is Miss Em and teaching art to children is what I love to do! I pride myself on creating dynamic, meaningful, and engaging art lessons that are taught in a relaxing and joyful way. I have over 20 years teaching experience in the elementary classroom and in the art studio, and I feel that I have a good grasp on how to create an environment that makes kids feel happy, motivated, confident, and successful.",
        "I look forward to seeing you in this Drawing and Watercolor Painting course.",
        "Let the creative fun begin! ",
      ],
      whoIsThisFor: [
        "This is a drawing and watercolor painting course designed for beginners.",
        "No drawing or painting experience is necessary to be successful in this course.",
      ],
      reviews: [
        {
          content: "Very fun",
          rating: 5.0,
          created_formatted_with_time_since: "2 weeks ago",
          userTitle: "amit J.",
          userInitials: "AJ",
        },
        {
          content:
            "i was a little depressed when i did this project, thinking it was too easy. Bu then I tried it, and as easy as it was it made me happier! I LOVED this experience!!!",
          rating: 5.0,
          created_formatted_with_time_since: "2 years ago",
          userTitle: "Rika S.",
          userInitials: "RS",
        },
        {
          content:
            "Yes, It is was great learning for me I thought that I would be difficult for me but something else! It was very easy!",
          rating: 5,
          created_formatted_with_time_since: "7 months  ago",
          userTitle: "Swati G.",
          userInitials: "SG",
        },
        {
          content:
            "Simply yet informative and productive. I felt so good learning to use water colour this way. Made me feel like a real artist.",
          rating: 5,
          created_formatted_with_time_since: "2 months ago",
          userTitle: "Arnel W.",
          userInitials: "AW",
        },
      ],

      content: [
        [
          [
            "Introduction, Course Goals, Examples of Projects, and Supplies Needed",
          ],
          [
            "Introduction to this Course",
            "Supplies and Materials Needed for This Course (Video)",
            "Supplies and Materials Needed for This Course (Document)",
          ],
        ],
        [
          ["Draw and Paint a Night Owl"],
          [
            "Introduction and Supplies Needed for This Project",
            "Step 1: Draw the Owl",
            "Step 2: Watercolor Paint the Owl",
          ],
        ],
        [
          ["Draw and Watercolor Paint a Shark"],
          [
            "Introduction and Supplies Needed for This Project",
            "Step 1: Draw the Shark",
            "Step 2: Paint the Shark",
          ],
        ],
        [
          ["Draw and Paint a Fish"],
          [
            "Introduction and Supplies Needed for This Project",
            "Step 1: Draw the Fish",
            "Step 2: Paint the Fish",
          ],
        ],
        [
          ["Draw and Paint a Dog"],
          [
            "Introduction and Supplies Needed for This Project",
            "Step 1: Draw a Dog",
            "Step 2: Paint the Dog",
          ],
        ],
        [
          ["Draw and Paint a Frog"],
          [
            "Introduction and Supplies Needed for This Project",
            "Step 1: Draw a Frog",
            "Step 2: Paint the Frog",
          ],
        ],
        [
          ["Draw and Paint a Dragonfly"],
          [
            "Introduction and Supplies Needed for This Project",
            "Step 1: Draw a Dragonfly",
            "Step 2: Paint the Dragonfly",
          ],
        ],
        [
          ["Draw and Paint a Rooster"],
          [
            "Introduction and Supplies Needed for This Project",
            "Step 1: Draw a Rooster",
            "Step 2: Paint the Rooster",
          ],
        ],
        [
          ["Draw and Paint a Fox"],
          [
            "Introduction and Supplies Needed for This Project",
            "Step 1: Draw a Fox",
            "Step 2: Paint the Fox",
          ],
        ],
        [
          ["Draw and Paint an Elephant"],
          [
            "Introduction and Supplies Needed for This Project",
            "Step 1: Draw an Elephant",
            "Step 2: Paint the Elephant",
          ],
        ],
        [
          ["Draw and Paint a Tiger Cat"],
          [
            "Introduction and Supplies Needed for This Project",
            "Step 1: Draw a Cat",
            "Step 2: Paint the Cat",
          ],
        ],
        [
          ["Draw and Paint a Horse"],
          [
            "Introduction to This Project and Supplies Needed",
            "Step 1: Draw a Horse",
            "Step 2: Watercolor Paint the Horse and the Background",
          ],
        ],
        [
          ["Draw and Paint a Butterfly"],
          [
            "Introduction to This Project and Supplies Needed",
            "Step 1: Draw a Butterfly Design",
            "Step 2: Paint the Background",
            "Step 3: Paint the Butterfly",
            "Step 4: Paint the Flowers",
          ],
        ],
        [
          ["Bonus Project: Draw and Paint a Koala"],
          [
            "Introduction to This Project and Supplies Needed",
            "Step 1: Draw a Koala Design",
            "Step 2: Paint the Background",
            "Step 3: Paint the Koala and Details",
          ],
        ],
        [
          ["Bonus Project: Draw and Paint a Moon Cat"],
          [
            "Introduction to This Project and Supplies Needed",
            "Step 1: Draw a Cat Design",
            "Step 2: Paint the Background",
            "Step 3: Paint the Cat",
          ],
        ],
        [
          ["Bonus Project: Draw and Paint a Porcupine in a Cozy Sweater"],
          [
            "Introduction to This Project and Supplies Needed",
            "Pattern Reference Sheet to Use for Ideas",
            "Step 1: Draw a Porcupine Design",
            "Step 2: Paint the Porcupine Design",
          ],
        ],
        [
          ["Thank You for Enrolling in This Course :)"],
          ["Thank You for Enrolling in This Course :)"],
        ],
      ],
    },
    {
      id: 3,
      link: "https://www.udemy.com/course/python-for-beginners-learn-programming-from-scratch/",
      title: "Python for Beginners - Learn Programming from scratch",
      instructor: 3,
      description:
        "Learn python and how to use it to analyze,visualize and present data. Includes tons of sample code and hours of video!",
      author: "Edwin Diaz, Coding Facutly Solutions",
      image: "https://img-c.udemycdn.com/course/240x135/405878_e5a0_3.jpg",
      price: "679.99",
      rating: 4.6,
      people: "1,781",
      category: "python",
      bestseller: false,
      learnings: [
        "To learn the python language",
        "To learn the CORE skills to understand any programming language",
      ],
      reviews: [
        {
          content:
            "i am a homemaker learning languages on udemy hoping for a better future , i hope this will help me in achieving what i want . I am so far able to understand lecture let 's see what comes ahead .",
          rating: 3.0,
          created_formatted_with_time_since: "3 weeks ago",
          userTitle: "Ashu C.",
          userInitials: "AC",
        },
        {
          content:
            "This was a great learning experience. It was fun and I learned a lot.",
          rating: 4.5,
          created_formatted_with_time_since: "4 months ago",
          userTitle: "Mike M.",
          userInitials: "MM",
        },
        {
          content:
            "In depth concepts of python have been clearly explained. Good chemistry between student and instructor. Fantastic course. Completed every vid and had lot of fun",
          rating: 5,
          created_formatted_with_time_since: "2 months  ago",
          userTitle: "Saurish R.",
          userInitials: "SR",
        },
        {
          content:
            "Yea in simple terms I really enjoyed this one and it was pretty easy to grab the concepts as a beginner, especially based on the way our instructor explained.",
          rating: 4,
          created_formatted_with_time_since: "2 weeks ago",
          userTitle: "Sagnik B.",
          userInitials: "SB",
        },
      ],
      ratingsSplit: [43, 39, 15, 2, 1],
      requirements: ["NO programming knowledge required "],
      descriptionDetailed: [
        "NEW PYTHON CODE ",
        "This python for beginners course is geared to students who want to know how python works and also to those totally new to programming.",
        "The python language has very simple syntax(way to write it) to learn and it is one of the most powerful languages to learn since it can used for a variety of things.",
        "Here are some: ",
        "1. Data analysis",
        "2. Game development",
        "3. Visualization",
        "4. Web development",
        "5. Robotics",
        "6. and more....",
        "Jobs in this field are really lucrative and knowing this language will give you an edge when finding a job and making a lot more money than other developers; python developers are not as many as in other languages since people think is hard. Python is super easy to learn but very powerful since it contains many possibilities.",
        "Python is growing faster and faster everyday and it has surpassed many other languages over the years for a lot of reasons, which you will find out soon enough.",
        "------------------------------------------------------------------------------------------",
        "Why take this course? ",
        "This course starts with explaining what programming really is? Have you ever wondered how things actually work in a program?",
        "1. Teaches the foundation of GENERAL programming ",
        "Every student should have some foundations on what programming really is before learning any language, why? Because once you understand the core components of programming it will be a lot easier to learn any language and create better programs.",
        "2. New lectures added all the time ",
        "When you like what you do, it reflects. This is not a job for me, so I wake up wanting to code and help my students. Basically you pay once, get the course forever and get extra values added all the time, you have to love that :)",
        "3. Fun place to be ",
        "I love making my lectures fun and engaging, so no boring lectures here!",
        "4. The support you get in this course in unmatched ",
        "have you ever joined a class and received very little support or none at all? Well that is not going to happen in this class, because I love helping my students.",
      ],
      whoIsThisFor: [
        "Student totally new to programming",
        "Student totally new to python",
      ],
      content: [
        [
          ["Programming fundamentals"],
          [
            "Introduction",
            "What is programming?",
            "What is source code?",
            "Compile VS Interpreted Languages",
            "Strings and numbers",
            "Variables",
            "Lists, Arrays or Collections",
            "Conditional Code - If statements",
            "Loops",
            "Functions",
          ],
        ],
        [
          ["Getting Started with Python"],
          [
            "intro to getting started",
            "What is Python?",
            "Installing Python",
            "Running Python IDLE and online",
            "Installing IDE",
          ],
        ],
        [
          ["Python Basics"],
          [
            "Intro to python basics",
            "Exercise files",
            "Strings  &amp; print function",
            "Numbers / Math",
            "Variables",
            "Lists",
            "Tuples",
            "Dictionaries",
          ],
        ],
        [
          ["Conditional structures"],
          [
            "intro to conditional code",
            "If Statements",
            "While Loop",
            "For loop",
            "Break and Continue",
          ],
        ],
        [
          ["Functions"],
          [
            "intro to functions",
            "Custom Functions &amp; arguments",
            "Functions with arguments",
            "Function variable scopes",
            "Function return",
            "Functions with flexible arguments",
            "Unpacking",
            "Modules",
            "Built in functions",
          ],
        ],
        [
          ["Working with files"],
          [
            "Intro to working files",
            "Opening / Creating files / Writing files",
            "File reading",
            "Renaming files",
            "Deleting files",
          ],
        ],
      ],
    },
    {
      id: 13,
      link: "https://www.udemy.com/course/complete-python-bootcamp/",
      title: "Introduction to Web Development",
      instructor: 5,
      description:
        "Are you Interested in Learning Web Development? Enroll in this Free course for a Dynamic Introduction to the Profession!",
      author: "Mark Lassoff",
      image: "https://img-b.udemycdn.com/course/240x135/99986_6cb4_10.jpg",
      price: "229.99",
      rating: 4.4,
      people: "1,734",
      category: "web development",
      bestseller: true,
      ratingsSplit: [43, 37, 15, 3, 2],
      reviews: [
        {
          content:
            "Es bueno pero creo que un poco desacualizado en algunos puntos, pero es entendible por el año publicado.",
          rating: 3.5,
          created_formatted_with_time_since: "2 months ago",
          userTitle: "Belem M.",
          userInitials: "BM",
        },
        {
          content:
            "It is giving a enough explanation.But one thing I suggested that help to learners by giving access for practicing.",
          rating: 4.0,
          created_formatted_with_time_since: "3 months ago",
          userTitle: "Venkata M.",
          userInitials: "VM",
        },
      ],
      learnings: [
        "Understand the technologies used in web development",
        "Identify the tools used by web developers",
        "Apply HTML document structure",
        "Write HTML allowing you to display a simple web page",
        "Add images to a web page",
        "Understand the role of CSS in web development",
        "Understand the HTML/CSS color model",
        "Apply colors to web page elements",
        "Alter CSS text properties",
        "Understand and apply the basics of the CSS box model",
        "Know the role of Javascript programming in web development",
        "Integrate prewritten Javascript code",
        "Create a basic Javascript program to collect data",
        "Use Javascript to adjust the appearance of page elements",
        "Understand the next steps to learning professional web development skills",
      ],
      requirements: [
        "Mac or PC",
        "Free Text editor (Brackets Recommended)",
        "Web Browser (Chrome and Firefox Recommended)",
      ],
      descriptionDetailed: [
        'Are you considering web development as a career? Do you simply want to learn to create your own web sites but don\'t know where to start? Does the world of programming fascinate you? Are you curious about "what it takes" to be a web developer.',
        "Join master instructor, Mark Lassoff, for this fast paced, short course designed to introduce you to the world of web development. You'll be introduced to three of the primary languages used for web development.",
        "Exposure to Three Major Programming Languages ",
        "First, Mark will introduce you to HTML5, HyperText Markup Language, used to contain the content elements of web and mobile sites. Next, you'll be introduced to CSS, Cascading StyleSheet Language, used to add design and style to web presentations. Finally, Mark will introduce you to Javascript, one of the most important and fastest growing languages used today.",
        "Dynamic Course Design ",
        "This course is designed to give you a preview of what professional web development work is like. You'll use some of the same languages and techniques used by professional web developers every day. With fascinating, fast paced lectures, code samples, and challenging lab exercises (solutions provided) you'll gain a sense of what it's like to work in the web development field.",
        "Thousands have learned web development and programming from Mark Lassoff. Join Introduction for Web Development today and start your path towards mastering this exciting and challenging field.",
      ],
      whoIsThisFor: [
        "Anyone who wants to start learning web development",
        "Beginners",
        "Students",
        "Teachers",
        "Traditional developers who want to learn web",
      ],
      content: [
        [
          ["Tools and HTML"],
          [
            "Introduction",
            "Development Tools",
            "Getting Started with HTML",
            "Images on web pages",
            "Section 1 Lab Exercise",
          ],
        ],
        [
          ["CSS"],
          [
            "Introducing CSS",
            "Using Color",
            "Box Model",
            "Section 2 Lab Exercise",
          ],
        ],
        [
          ["Javascript"],
          [
            "Inserting Javascript",
            "Writing Javascript",
            "Making a Form",
            "Where to Go From Here?",
            "Section 3 Lab Exercise",
          ],
        ],
        [["Bonus Lecture"], ["Bonus Lecture"]],
      ],
    },
  ],
  instructors: [
    {
      id: 1,
      photo: "https://img-c.udemycdn.com/user/200_H/10260436_946b_6.jpg",
      title: "CEO of TheCodex.me - Teaching 500,000+ Students how to code",
      name: "Avinash Jain",
      rating: 4.4,
      students: "891,073",
      about: [
        "Avinash Jain is currently a senior at UC Berkeley majoring in Electrical Engineering and Computer Science. He's the CEO and Founder of TheCodex, an online educational platform focused on bringing the best programming content to hundreds of thousands of students around the world.",
        "His programming journey began at the age of 10, starting off with simple Python scripts to crawl the weather. Since then, he's worked at numerous companies and is professionally experienced in Python, iOS Development and Web Development. He's launched a plethora of applications in the App Store amassing thousands of downloads. Additionaly, he's competed and won in several hackathons around the world including PennApps and NWHacks.",
        "Avinash has a passion to teach - his enthusiasm and love for programming is evident in every video. For the past 7 years he's been an instructor on Udemy and he loves motivating and enabling others to pursue their programming dreams. He hopes to help students realize the power of programming and jumpstart their careers through his courses.",
        "Checkout TheCodex for all of his courses, fantastic discounts, and any guidance or help.",
      ],
      courses: 16,
      reviews: "73,790",
    },
    {
      id: 2,
      photo: "https://img-b.udemycdn.com/user/200_H/9685726_67e7_4.jpg",
      title: "Head of Data Science at Pierian Training",
      name: "Jose Portilla",
      rating: 4.6,
      students: "3,006,323",
      about: [
        "Jose Marcial Portilla has a BS and MS in Mechanical Engineering from Santa Clara University and years of experience as a professional instructor and trainer for Data Science, Machine Learning and Python Programming. He has publications and patents in various fields such as microfluidics, materials science, and data science. Over the course of his career he has developed a skill set in analyzing data and he hopes to use his experience in teaching and data science to help other people learn the power of programming, the ability to analyze data, and the skills needed to present the data in clear and beautiful visualizations. Currently he works as the Head of Data Science for Pierian Training and provides in-person data science and python programming training courses to employees working at top companies, including General Electric, Cigna, The New York Times, Credit Suisse, McKinsey and many more. Feel free to check out the website link to find out more information about training offerings.",
      ],
      courses: 54,
      reviews: "938,439",
    },
    {
      id: 3,
      photo: "https://img-b.udemycdn.com/user/200_H/6772884_fcfc_2.jpg",
      title: "Web Developer & Premium Instructor - 800,000 students",
      name: "Edwin Diaz",
      rating: 4.4,
      students: "828,487",
      about: [
        "Edwin Diaz is a software and web technologies engineer, a life coach trainer who is also a serial entrepreneur with multiple online businesses, ranging from online jewelry shops, affiliate websites, application development and consultations services, personal online schools, etc.",
        "With over one million students, and clients growing by the thousands a day, Mr. Diaz lets the numbers speak for themselves.",
        "Founding multiple online companies have allowed Mr. Diaz to have the time to teach others. He currently teaches web technologies on different online platforms. He also teaches life coaching sessions to help others achieve a high level of success in many areas of life.",
        "For Mr. Diaz, there is nothing more rewarding than helping others become successful.",
        'His ability to transmit energy, enthusiasm, and complex knowledge allows him to do what he does best "Teach".',
        "Teaching is not just a job for Mr. Diaz but a way of life that continues to flourish every single day.",
        "Apart from teaching he enjoys spending part of his time with his family.",
      ],
      courses: 47,
      reviews: "123,267",
    },
    {
      id: 4,
      photo: "https://img-b.udemycdn.com/user/200_H/9100824_a767_2.jpg",
      title: "Teacher, Art Instructor, Artist",
      name: "Em Winn",
      rating: 4.6,
      students: "121,487",
      about: [
        "Hi. My name is Em Winn and teaching art to children is what I love to do! I pride myself on creating dynamic, meaningful, and engaging art lessons that are taught in a relaxing and joyful way. I have over 20 years teaching experience in the elementary classroom and in the art studio, and I feel that I have a good grasp on how to create an environment that makes kids feel happy, motivated, confident, and successful. Let the creative fun begin!",
      ],
      courses: 23,
      reviews: "13,267",
    },
    {
      id: 5,
      photo: "https://img-b.udemycdn.com/user/200_H/22632534_6ae1.jpg",
      title: "Programming Instructor with over 500,000 students worldwide.",
      name: "Mark Lassoff",
      rating: 4.4,
      students: "92,076",
      about: [
        "Mark Lassoff 's parents frequently claim that Mark was born to be a programmer.  Starting, in the mid-eighties at age 11, Mark was hard at work on his Commodore 64 writing games in the BASIC language.  After completing a computer science degree, Mark developed software for several well-known internet startups during the initial internet boom of the mid 1990’s.  Five years ago Mark parlayed a two decades of software development experience into his latest entrepreneurial venture, LearnToProgram Media.",
        "LearnToProgram Media publishes online courses that teach mobile, web, and game development. Over 500,000 people have learned programming from Mark through online classes he has either authored or published. In addition to publishing popular courses and books LearnToProgram Media operates an internet video network which produces several programs on software development.",
        "Previously Mark founded PowerPlant Marketing, which created marketing automation software for REALTORS™.  After the sale of PowerPlant, Mark went on to found Internet Broadcasting Group which counted among it’s launch clients Nike, Blue Moon Brewing Company and Opubco.",
        "Mark lives in Connecticut and speaks worldwide on software development, entrepreneurship and online learning.  He has spoken at TechWeek NY, TechWeek LA, and SXSW, among other large conferences.  In his spare time he he enjoys aviation, mentoring new business owners and spending time with life-long friends and family.",
      ],
      courses: 25,
      reviews: "9,167",
    },
  ],
};
